name: Backend CI Pipeline
run-name: ${{ github.actor }} is testing CI pipeline 🚀
on:
  push:
    branches:
      - main
jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend CI pipeline start 🚀"
