name: ci pipeline - develop environment
run-name: ${{ github.actor }} is testing CI pipeline - develop 🚀
on:
  push:
    branches:
      - develop
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Backend CI pipeline start 🚀"
